name: Dev Workflow - Test and check thing

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Maven package
      run: mvn -B clean package -DskipTests

    - name: Maven verify
      run: mvn -B clean verify

  coverage:
    name: Run Test Suites
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Test with Maven
        run: mvn -B clean verify

      - name: Upload coverage to Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)